### ISSUE TITLE
suggestion for better support for Python 2.x

### ISSUE THREAD

**Issue by jpeyret** [toymakerlabs/django-webpack-scaffolding#1]
First, a big thank you for this excellent writeup!

I need to use Python 2.7 and I found the initial Django-webpack interaction and configuration to work well enough.  Except that `DJANGO_SETTINGS_MODULE="projectname.config.settings_development"` doesn't work and fails with `ImportError: No module named config.settings_development`.

It is easy enough to fix, all that's missing is an empty **config\\\__init\__.py**. (created via **touch** works).   Python 3 assumes it implicitly and does not need it.  Python 2.x does need it but it can be empty.  In both cases, it will be executed if there is something in it.

Some writeup about that here:  http://stackoverflow.com/a/37140173/1394353

**Comment by toymakerlabs** [comment]
@jpeyret thanks for your feedback on this! Appreciate your suggestion - apologies for the delay! I fixed this and will update the docs. It should work with Python 2.7 now. Cheers
